export const REFRESH_CHANGELOGS = 'REFRESH_CHANGELOGS'
export const CLEAR_CHANGELOGS = 'CLEAR_CHANGELOGS'
export const REFRESH_LATEST_VERSIONS = 'REFRESH_VERSIONS'
export const REFRESH_SETTINGS = 'REFRESH_SETTINGS'
