export const SET_RELEASES = 'SET_RELEASES'
export const SET_LATEST_VERSIONS = 'REFRESH_VERSIONS'
export const SET_SETTINGS = 'REFRESH_SETTINGS'
export const SET_CHANGELOGS_MD_FILES = 'SET_VUE_ROUTER_MD'
